### ISSUE TITLE
Failed to load plugin error

### ISSUE THREAD

**Issue by BlankSky21** [LuxLuma/Luxs-Model-Changer#17]
The error in the console is saying:

[SM] Failed to load plugin "LMCL4D1CDeathHandler.smx": Plugin only supports Left 4 Dead.
[SM] Failed to load plugin "LMCL4D1SetTransmit.smx": Plugin only supports Left 4 Dead.
[SM] Failed to load plugin "LMC_L4D1_Menu_Choosing.smx": Plugin only supports Left 4 Dead.
[SM] Failed to load plugin "LMC_L4D1_RandomSpawns.smx": Plugin only supports Left 4 Dead.

I've used this plugin on my server before, could it be because I'm using SourceMod 1.11 or because of the new left 4 dead 2 update?

**Comment by LuxLuma** [comment]
That error is because you are trying to load modules that are for Left 4 Dead.
**Plugin only supports Left 4 Dead.**

If you are running LMC with all of it's modules on Left 4 Dead 2 remove the L4D1 variants.
