### ISSUE TITLE
Exception reported: Script execution timed out

### ISSUE THREAD

**Issue by MilanesaTM** [LuxLuma/Luxs-Model-Changer#19]
Exception reported: Script execution timed out
Blaming: LMC_L4D2_Menu_Choosing.smx
Call stack trace:
  [1] Line 343, D:\Github\Luxs-Model-Changer\addons\sourcemod\scripting\LMC_L4D2_Menu_Choosing.sp::OnMapStart

Edit: Maybe i'm missing a map_start_check.smx or something of that style...?

**Comment by LuxLuma** [comment]
There is a fix for this allowing more time for the plugin to load models no way around other than more time.
https://forums.alliedmods.net/showpost.php?p=2721135&postcount=236
